#!/usr/bin/env bash

# Install Go tools
echo 'Installing Go tools...'
go get -u golang.org/x/tools/cmd/goimports
go get -u github.com/tools/godep
go get -u github.com/golang/lint/golint
go get -u golang.org/x/tools/cmd/gotype
