#!/usr/bin/env bash

# Delete previous vim directory
rm -rf ~/.vim
mkdir -p ~/.vim

# Vim Plug installation
if [ ! -e ~/.vim/autoload/plug.vim ]; then
  curl -fsSLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u ~/.vimrc.bundles +PlugInstall +PlugClean! +qa

# Start and stop vim
vim -c 'q'
