#!/usr/bin/env bash

SCRIPTS_PATH=$(dirname "${BASH_SOURCE}")/scripts

# Require admin permissions
sudo -v

# Update sudo time until script finishes
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Scripts
source $SCRIPTS_PATH/osx
source $SCRIPTS_PATH/brew
sudo chsh -s $(which zsh) $(whoami)
/usr/bin/env zsh $SCRIPTS_PATH/zprezto
source $SCRIPTS_PATH/ssh

# Download base16 shell colors
git clone https://github.com/chriskempson/base16-shell.git ~/.colors/base16
