#!/usr/bin/env bash

# Install brew if not installed
if ! $(command -v brew >/dev/null 2>&1 || { exit 1; }); then
  echo 'Installing brew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update brew
echo 'Updating brew...'
brew update

# Upgrade formulas
brew upgrade --all

# Install zsh
brew install zsh
ZSH_PATH=$(which zsh)
if ! grep -q -x -F -e "${ZSH_PATH}" < /etc/shells; then
  echo "${ZSH_PATH}" |  sudo tee -a /etc/shells > /dev/null
fi

# Add formulae
brew tap 'homebrew/dupes'
brew tap 'thoughtbot/formulae'

# Install core utils
brew install coreutils
brew install findutils
brew install moreutils
brew install openssl

# Update built-in tools
brew install ack
brew install git
brew install gnu-sed --default-names
brew install gnu-tar --default-names
brew install homebrew/dupes/grep
brew install homebrew/dupes/openssh
brew install python
brew install vim --with-override-system-vi --with-lua --with-python

# Install additional packages
brew install go
brew install htop-osx
brew install node
brew install p7zip
brew install python3
brew install reattach-to-user-namespace
brew install rename
brew install screenfetch
brew install ssh-copy-id
brew install tmux --HEAD
brew install tree
brew install watch

# Remove outdated versions
brew cleanup
