#!/usr/bin/env bash

# Download patched fonts
tmpDir=$(mktemp -d)
startDir=$(pwd)
cd $tmpDir
git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git
cd nerd-fonts
./install.sh
cd $startDir
rm -rf $tmpDir
