#!/usr/bin/env bash

# Install Go tools
echo 'Installing Go tools...'
go get -u golang.org/x/tools/cmd/goimports
go get -u github.com/tools/godep
go get -u golang.org/x/tools/cmd/gotype
go get -u github.com/nsf/gocode
go get -u github.com/rogpeppe/godef
go get -u github.com/golang/lint/golint
go get -u github.com/lukehoban/go-outline
go get -u golang.org/x/tools/cmd/gorename
go get -u github.com/tpng/gopkgs
go get -u github.com/newhook/go-symbols
go get -u golang.org/x/tools/cmd/guru