#!/usr/bin/env bash

# Delete previous vim directory
rm -rf ~/.vim
mkdir -p ~/.vim

# Vim Plug installation
if [ ! -e ~/.vim/dein/repos/github.com/Shougo/dein.vim ]; then
  git clone https://github.com/Shougo/dein.vim.git ~/.vim/dein/repos/github.com/Shougo/dein.vim
fi
vim -N -u ~/.vimrc.bundles '+call dein#install()' +qa

# Start and stop vim
vim -c 'q'
